import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Ladorm",
//   description: "Generated by Ladorm",
// };

export const metadata: Metadata = {
  title: "Ladorm",
  description: "Asrama Mahasiswa Gorontalo - Tempat nyaman dan terjangkau.",
  openGraph: {
    title: "Ladorm - Asrama Mahasiswa Gorontalo",
    description: "Tempat nyaman dan terjangkau untuk mahasiswa Gorontalo.",
    url: "https://student-dormitory.vercel.app",
    siteName: "Ladorm",
    images: [
      {
        url: "https://student-dormitory.vercel.app/images/asrama_profile_img.webp",
        width: 1200,
        height: 630,
        alt: "Ladorm - Asrama Mahasiswa Gorontalo",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Ladorm - Asrama Mahasiswa Gorontalo",
    description: "Tempat nyaman dan terjangkau untuk mahasiswa Gorontalo.",
    images: [
      "https://student-dormitory.vercel.app/images/asrama_profile_img.webp",
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
